stages:
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - configs/experiment/finetune.yaml
      - data/dogs_dataset

  eval:
    cmd: python src/eval.py
    deps:
      - src/eval.py
      - configs/experiment/finetune.yaml
      - data/dogs_dataset

  infer:
    cmd: python src/infer.py
    deps:
      - src/infer.py
      - configs/experiment/finetune.yaml
      - data/dogs_dataset
